// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnz2O3WEeY5RwFCaTCHfESErbtyvZMOOs',
    appId: '1:940836680630:web:0d92ea959f5e2c8ae74717',
    messagingSenderId: '940836680630',
    projectId: 'kratos-3d',
    authDomain: 'kratos-3d.firebaseapp.com',
    storageBucket: 'kratos-3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1vBPAz1C3heM08Y--KRCqoaihwm-hFw',
    appId: '1:940836680630:android:bc02b05bf35f70dce74717',
    messagingSenderId: '940836680630',
    projectId: 'kratos-3d',
    storageBucket: 'kratos-3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-DuGpN3VcD0G8VIJo5X57m5bZoeHXug',
    appId: '1:940836680630:ios:c9febc92f7ca4da3e74717',
    messagingSenderId: '940836680630',
    projectId: 'kratos-3d',
    storageBucket: 'kratos-3d.appspot.com',
    iosBundleId: 'com.example.kratos3dProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-DuGpN3VcD0G8VIJo5X57m5bZoeHXug',
    appId: '1:940836680630:ios:c9febc92f7ca4da3e74717',
    messagingSenderId: '940836680630',
    projectId: 'kratos-3d',
    storageBucket: 'kratos-3d.appspot.com',
    iosBundleId: 'com.example.kratos3dProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnz2O3WEeY5RwFCaTCHfESErbtyvZMOOs',
    appId: '1:940836680630:web:41f15a278b5d7dd1e74717',
    messagingSenderId: '940836680630',
    projectId: 'kratos-3d',
    authDomain: 'kratos-3d.firebaseapp.com',
    storageBucket: 'kratos-3d.appspot.com',
  );
}
